--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 10.0.1009
--   Created On : reede, 31 jaanuar, 2014 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS `eco_basket` CASCADE
;
DROP TABLE IF EXISTS `eco_discount` CASCADE
;
DROP TABLE IF EXISTS `eco_invoice` CASCADE
;
DROP TABLE IF EXISTS `eco_order` CASCADE
;
DROP TABLE IF EXISTS `eco_order_line` CASCADE
;
DROP TABLE IF EXISTS `eco_payment` CASCADE
;
DROP TABLE IF EXISTS `eco_product` CASCADE
;
DROP TABLE IF EXISTS `eco_user` CASCADE
;

--  Create Tables 
CREATE TABLE `eco_basket`
(
	`session_id` VARCHAR(255) NOT NULL,
	`basket_data` BLOB NOT NULL,
	PRIMARY KEY (`session_id`)

) 
;


CREATE TABLE `eco_discount`
(
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`type` VARCHAR(255) NOT NULL,
	`label` VARCHAR(255) NOT NULL,
	`amount` INTEGER NOT NULL,
	PRIMARY KEY (`id`)

) 
;


CREATE TABLE `eco_invoice`
(
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`order_id` INTEGER UNSIGNED NOT NULL,
	`due_amount` INTEGER NOT NULL,
	`due_datetime` DATETIME,
	`created` DATETIME NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`order_id`)

) 
;


CREATE TABLE `eco_order`
(
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INTEGER UNSIGNED NOT NULL,
	`status` VARCHAR(20) NOT NULL,
	`due_amount` INTEGER NOT NULL,
	`created` DATETIME NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`user_id`)

) 
;


CREATE TABLE `eco_order_line`
(
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`order_id` INTEGER UNSIGNED NOT NULL,
	`product_id` INTEGER UNSIGNED NOT NULL,
	`quantity` DECIMAL(10,2) NOT NULL,
	`due_amount` INTEGER NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`order_id`),
	KEY (`product_id`)

) 
;


CREATE TABLE `eco_payment`
(
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INTEGER UNSIGNED,
	`order_id` INTEGER UNSIGNED NOT NULL,
	`bank_code` VARCHAR(20) NOT NULL,
	`amount` VARCHAR(255) NOT NULL,
	`status` VARCHAR(20) NOT NULL,
	`data_dump` BLOB NOT NULL,
	`created` DATETIME NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`order_id`),
	KEY (`user_id`)

) 
;


CREATE TABLE `eco_product`
(
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255),
	`price` INTEGER NOT NULL,
	`vat` DECIMAL(3,2),
	PRIMARY KEY (`id`)

) 
;


CREATE TABLE `eco_user`
(
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255),
	PRIMARY KEY (`id`)

) 
;



SET FOREIGN_KEY_CHECKS=1;


--  Create Foreign Key Constraints 
ALTER TABLE `eco_invoice` ADD CONSTRAINT `FK_eco_invoice_eco_order` 
	FOREIGN KEY (`order_id`) REFERENCES `eco_order` (`id`)
;

ALTER TABLE `eco_order` ADD CONSTRAINT `FK_eco_order_eco_user` 
	FOREIGN KEY (`user_id`) REFERENCES `eco_user` (`id`)
;

ALTER TABLE `eco_order_line` ADD CONSTRAINT `FK_eco_order_line_eco_order` 
	FOREIGN KEY (`order_id`) REFERENCES `eco_order` (`id`)
;

ALTER TABLE `eco_order_line` ADD CONSTRAINT `FK_eco_order_line_eco_product` 
	FOREIGN KEY (`product_id`) REFERENCES `eco_product` (`id`)
;

ALTER TABLE `eco_payment` ADD CONSTRAINT `FK_eco_payment_eco_order` 
	FOREIGN KEY (`order_id`) REFERENCES `eco_order` (`id`)
;

ALTER TABLE `eco_payment` ADD CONSTRAINT `FK_eco_payment_eco_user` 
	FOREIGN KEY (`user_id`) REFERENCES `eco_user` (`id`)
;
